# Set to false if OpenShift GitOps is already installed on the hub cluster (or
# if the openshift-gitops namespace already exists).
createOpenShiftGitOpsNamespace: true

# List of clusters. If your environment will have additional clusters, those
# would go here.
clusters:
  # clusterName should match cluster's name in ACM
- clusterName: local-cluster # Hub cluster in ACM is always called "local-cluster"
  # chartName should match the name of the chart (in Chart.yaml) of the GitOps
  # Helm chart in the GitOps repo for this environment
  chartName: gitops-hub
  # repoUrl should be a full path to the GitOps repo for this environment.
  # Should end with ".git".
  repoUrl: https://github.com/jayissi/Sandbox-GitOps.git

