# All clusters need OpenShift GitOps to be installed so that the Argo CD
# Applications in the cluster's GitOps repo can be deployed. This policy will
# deploy OpenShift GitOps on all clusters managed by ACM.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-operator
  namespace: bootstrap
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-operator
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
                  name: openshift-gitops-operator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: openshift-gitops-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-operator
  namespace: bootstrap
spec:
  clusterConditions: []
  clusterSelector:
    matchExpressions:
      - key: cluster.open-cluster-management.io/clusterset
        operator: In
        values:
          - default
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-operator
  namespace: bootstrap
placementRef:
  name: openshift-gitops-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: openshift-gitops-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
